master: temporarily set fixed revision to meta-oe
poky & meta-oe master branches are out of sync due drop of
python3-wheel in meta-oe (c720dc971 - python3-wheel: drop; moved to oe-core)
and the inclusion of it in poky currently only in master-next branch
(130b87f25b - python3-wheel: move 0.37.1 from meta-python)
causing build error:

ERROR: Nothing RPROVIDES 'python3-wheel-native' (but
/home/qt/work/build/meta-openembedded/meta-python/recipes-devtools/python/python3-setuptools-rust-native_1.1.2.bb
RDEPENDS  on or otherwise requires it)

Change-Id: I882ac431a311483586d2f368df187ea9e2d0c044
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>