qcom/6.7: freeze meta-boot2qt-qcom layer
Freeze meta-boot2qt-qcom layer to revision
compatible with 6.7 builds. meta-virtualization layer
was added for 6.8 onwards.

Fixes build issue:
ERROR: The following layer directories do not exist:
ERROR:    /home/qt/work/sources/meta-virtualization
ERROR: Please check BBLAYERS in /home/qt/work/build/conf/bblayers.conf

Change-Id: I6aab7fdd5298bb9cdca2d89d97af08cca31c0e51
Reviewed-by: Alex Bu <alex.bu@qt.io>